ETS-2157 - removes js calculated position of Skyscraper
tourstream/fti-portal-styleguide pull request #135
Opened 2019-07-23 08:19 UTC by virgilchiriac

2019-07-23 08:49 UTC, BirgitPohl approved these changes
👍🏻Awesome. It's a much easier solution. Thank you for contributing to it.

2019-07-23 08:49 UTC, dknx01 submitted a review, later dismissed

2019-07-23 09:11 UTC, susannegernandt submitted a review, later dismissed

2019-07-23 13:51 UTC, BirgitPohl commented on CHANGELOG.md
> +## 0.43.5
Since Claudia merged her PR, you need to update your version.

2019-07-24 07:42 UTC, BirgitPohl requested changes
Also, when merging, try to squash the commits before. Thank you. There is the option to squash merge on Github.

2019-07-24 07:42 UTC, BirgitPohl commented on CHANGELOG.md
> +- Removes js positioning of Skyscraper
Since Claudia merged her PR, you need to update your version.

2019-07-24 15:10 UTC, BirgitPohl approved these changes

2019-07-24 15:12 UTC, merged